namespace :src do
  desc 'Init 1C application src'
  task :init do
    $LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
    require 'hackathon'
    app_spec = Hackathon::Application.specification
    app_spec.src.init_src
  end
end

